### ISSUE TITLE
Build of docdoku-plm-server-office-doc failed due to dependency resolving failure

### ISSUE THREAD

**Issue by amottier** [docdoku/docdoku-plm-server#1]
The dependency declared in https://github.com/docdoku/docdoku-plm-server/blob/0a5d5f4b8ca629078d077eeca658967b61d70e84/pom.xml#L146 cannot be resolved because version `1.0.0` of `com.github.ralfstuckert.pdfbox-layout:pdfbox-layout` is in error on https://jitpack.io/#ralfstuckert/pdfbox-layout

Issue seems to already been [reported](https://github.com/jitpack/jitpack.io/issues/4520) to JitPack.

**Comment by amottier** [comment]
A workaround using MuleSoft repository is documented here: https://github.com/grasshopper7/extentreports-cucumber6-adapter/issues/36#issuecomment-817551411

**Comment by mguimard** [comment]
Merged, thank you

**Comment by amottier** [comment]
Thanks for the merge. I can confirm that build is now successful :slightly_smiling_face:
